version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tfc-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: tfc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
